[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-cors>=6.0.1",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "openai>=1.92.2",
    "psycopg2-binary>=2.9.10",
    "trafilatura>=2.0.0",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "numpy>=2.3.1",
    "docx>=0.2.4",
    "werkzeug>=3.1.3",
    "google-genai>=1.22.0",
    "langchain>=0.3.26",
    "langchain-groq>=0.3.4",
    "langchain-google-genai>=2.0.10",
    "langchain-community>=0.3.26",
    "faiss-cpu>=1.11.0",
    "deep-translator>=1.11.4",
    "groq>=0.29.0",
    "google-generativeai>=0.8.5",
]
